//pipeline steps configuration
steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCredential
    integrationFlowId: P013346-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCredential
    integrationFlowId: P013346-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCredential
    integrationFlowId: P013346-flow4
    integrationFlowName: P013346-flow4
    packageId: CICD
    filePath: P013346-flow4.zip
